name: EventFilter
main: net.yzimroni.eventfilter.plugin.EventFilterPlugin
version: 0.1
description: Event filter plugin
authors: [yzimroni]
commands:
  eventfilter:
    description: event filter
    aliases: [ef, filter, event]